services:
  - type: web
    name: uno
    env: node
    region: ohio
    plan: free
    buildCommand: pnpm install && pnpm --filter @uno/shared build && pnpm --filter @uno/server build && pnpm --filter @uno/client build
    startCommand: pnpm --filter @uno/server start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
